/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.emanuelegargiulo.filelister;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * Class responsible of showing the graphic component of the project.
 * @author emanuelegargiulo
 */
public class ExtensionPicker extends javax.swing.JFrame {

    public boolean firstAttempt = true;

    /**
     * Creates new form ExtensionPicker
     */
    public ExtensionPicker() {
        initComponents();
        chooser.setControlButtonsAreShown(false);
        setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        audioCB = new javax.swing.JCheckBox();
        picturesCB = new javax.swing.JCheckBox();
        videoCB = new javax.swing.JCheckBox();
        documentsCB = new javax.swing.JCheckBox();
        GenListButton = new javax.swing.JButton();
        customExt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        GenListAll = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        chooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        loggerTextarea = new javax.swing.JTextArea();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pick file types");
        setResizable(false);

        jLabel1.setText("Select the type of files you want to list");

        audioCB.setText("Audio");
        audioCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioCBActionPerformed(evt);
            }
        });

        picturesCB.setText("Pictures");
        picturesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picturesCBActionPerformed(evt);
            }
        });

        videoCB.setText("Video");
        videoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoCBActionPerformed(evt);
            }
        });

        documentsCB.setText("Documents");
        documentsCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentsCBActionPerformed(evt);
            }
        });

        GenListButton.setText("List Selected Types");
        GenListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenListButtonActionPerformed(evt);
            }
        });

        customExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customExtActionPerformed(evt);
            }
        });

        jLabel3.setText("Add further custom extensions, separated by commas (es: zip, exe)");

        GenListAll.setText("List All Files");
        GenListAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenListAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customExt, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(audioCB)
                        .addGap(80, 80, 80)
                        .addComponent(videoCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(picturesCB)
                        .addGap(80, 80, 80)
                        .addComponent(documentsCB)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(GenListButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GenListAll))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {audioCB, documentsCB, picturesCB, videoCB});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(audioCB)
                    .addComponent(videoCB)
                    .addComponent(documentsCB)
                    .addComponent(picturesCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customExt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenListAll, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel2.setText("No selection lists all files");

        chooser.setApproveButtonText("");
        chooser.setApproveButtonToolTipText("");
        chooser.setDialogTitle("Choose Source Folder");
        chooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        chooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooserActionPerformed(evt);
            }
        });

        loggerTextarea.setEditable(false);
        loggerTextarea.setBackground(new java.awt.Color(0, 0, 0));
        loggerTextarea.setColumns(20);
        loggerTextarea.setForeground(new java.awt.Color(0, 255, 51));
        loggerTextarea.setRows(5);
        loggerTextarea.setDragEnabled(false);
        jScrollPane1.setViewportView(loggerTextarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel2)))
                        .addGap(257, 257, 257))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(chooser, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void audioCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_audioCBActionPerformed

    private void picturesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picturesCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_picturesCBActionPerformed

    private void videoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_videoCBActionPerformed

    private void documentsCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentsCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentsCBActionPerformed

    private void GenListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenListButtonActionPerformed
        addCustExt();
        if (audioCB.isSelected()) {
            ExtensionsAdder.addAudio();
        }
        if (picturesCB.isSelected()) {
            ExtensionsAdder.addPics();
        }
        if (videoCB.isSelected()) {
            ExtensionsAdder.addVideo();
        }
        if (documentsCB.isSelected()) {
            ExtensionsAdder.addDocs();
        }
        try {
            GetList.getList(chooser.getSelectedFile().getAbsolutePath(), ExtensionsAdder.getFilter(), this);
        } catch (NullPointerException e) {
            if (firstAttempt) {
                GetList.getList(chooser.getCurrentDirectory().getAbsolutePath(), ExtensionsAdder.getFilter(), this);
                firstAttempt = false;
            } else {
                textLogger("ERROR. Try selecting a different location");
            }
        }
    }//GEN-LAST:event_GenListButtonActionPerformed

    private void chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooserActionPerformed

    private void customExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customExtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customExtActionPerformed

    private void GenListAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenListAllActionPerformed
        try {
            GetList.getList(chooser.getSelectedFile().getAbsolutePath(), ExtensionsAdder.getFilter(), this);
        } catch (NullPointerException e) {
            if (firstAttempt) {
                GetList.getList(chooser.getCurrentDirectory().getAbsolutePath(), null, this);
                System.out.println("First attempt at folder selection has failed. Retrying...");
                firstAttempt = false;
            } else {
                textLogger("ERROR. Try selecting a different location");
                System.out.println("ERROR. Try selecting a different location");
            }
        }
    }//GEN-LAST:event_GenListAllActionPerformed

    /**
     * Main class, launches ExtensionPicker after setting the app's look and feel
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExtensionPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExtensionPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExtensionPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExtensionPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ExtensionPicker.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(ExtensionPicker.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(ExtensionPicker.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(ExtensionPicker.class.getName()).log(Level.SEVERE, null, ex);
                }
                new ExtensionPicker();
            }
        });

    }

    /**
     * Allows output to the built-in text area
     * @param text : the text to write in the textarea
     */
    public void textLogger(String text) {
        loggerTextarea.append(text + "\n");
    }

    /**
     * Adds the custom extensions typed by the user to the filter
     */
    public void addCustExt() {
        String toAdd = customExt.getText();
        String[] extensions = toAdd.split(",");
        ExtensionsAdder.addExtensions(extensions);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenListAll;
    private javax.swing.JButton GenListButton;
    private javax.swing.JCheckBox audioCB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFileChooser chooser;
    private javax.swing.JTextField customExt;
    private javax.swing.JCheckBox documentsCB;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea loggerTextarea;
    private javax.swing.JCheckBox picturesCB;
    private javax.swing.JCheckBox videoCB;
    // End of variables declaration//GEN-END:variables
}
